-- TSLean.Scanner.Keywords: Keyword lookup table mapping strings to SyntaxKind.
-- Mirrors TypeScript's textToKeyword map.

import Std.Data.HashMap
import TSLean.Ast.SyntaxKind

namespace TSLean.Scanner

open TSLean.Ast

/-- Map from keyword text to SyntaxKind. Built once at initialization. -/
def textToKeyword : Std.HashMap String SyntaxKind :=
  let entries : Array (String × SyntaxKind) := #[
    -- Reserved words (ECMAScript)
    ("break",       .breakKeyword),
    ("case",        .caseKeyword),
    ("catch",       .catchKeyword),
    ("class",       .classKeyword),
    ("const",       .constKeyword),
    ("continue",    .continueKeyword),
    ("debugger",    .debuggerKeyword),
    ("default",     .defaultKeyword),
    ("delete",      .deleteKeyword),
    ("do",          .doKeyword),
    ("else",        .elseKeyword),
    ("enum",        .enumKeyword),
    ("export",      .exportKeyword),
    ("extends",     .extendsKeyword),
    ("false",       .falseKeyword),
    ("finally",     .finallyKeyword),
    ("for",         .forKeyword),
    ("function",    .functionKeyword),
    ("if",          .ifKeyword),
    ("import",      .importKeyword),
    ("in",          .inKeyword),
    ("instanceof",  .instanceOfKeyword),
    ("new",         .newKeyword),
    ("null",        .nullKeyword),
    ("return",      .returnKeyword),
    ("super",       .superKeyword),
    ("switch",      .switchKeyword),
    ("this",        .thisKeyword),
    ("throw",       .throwKeyword),
    ("true",        .trueKeyword),
    ("try",         .tryKeyword),
    ("typeof",      .typeOfKeyword),
    ("var",         .varKeyword),
    ("void",        .voidKeyword),
    ("while",       .whileKeyword),
    ("with",        .withKeyword),
    -- Strict mode reserved words
    ("implements",  .implementsKeyword),
    ("interface",   .interfaceKeyword),
    ("let",         .letKeyword),
    ("package",     .packageKeyword),
    ("private",     .privateKeyword),
    ("protected",   .protectedKeyword),
    ("public",      .publicKeyword),
    ("static",      .staticKeyword),
    ("yield",       .yieldKeyword),
    -- Contextual keywords
    ("abstract",    .abstractKeyword),
    ("accessor",    .accessorKeyword),
    ("as",          .asKeyword),
    ("asserts",     .assertsKeyword),
    ("assert",      .assertKeyword),
    ("any",         .anyKeyword),
    ("async",       .asyncKeyword),
    ("await",       .awaitKeyword),
    ("boolean",     .booleanKeyword),
    ("constructor", .constructorKeyword),
    ("declare",     .declareKeyword),
    ("get",         .getKeyword),
    ("infer",       .inferKeyword),
    ("intrinsic",   .intrinsicKeyword),
    ("is",          .isKeyword),
    ("keyof",       .keyOfKeyword),
    ("module",      .moduleKeyword),
    ("namespace",   .namespaceKeyword),
    ("never",       .neverKeyword),
    ("out",         .outKeyword),
    ("readonly",    .readonlyKeyword),
    ("require",     .requireKeyword),
    ("number",      .numberKeyword),
    ("object",      .objectKeyword),
    ("satisfies",   .satisfiesKeyword),
    ("set",         .setKeyword),
    ("string",      .stringKeyword),
    ("symbol",      .symbolKeyword),
    ("type",        .typeKeyword),
    ("undefined",   .undefinedKeyword),
    ("unique",      .uniqueKeyword),
    ("unknown",     .unknownKeyword),
    ("using",       .usingKeyword),
    ("from",        .fromKeyword),
    ("global",      .globalKeyword),
    ("bigint",      .bigIntKeyword),
    ("override",    .overrideKeyword),
    ("of",          .ofKeyword)
  ]
  entries.foldl (fun m (k, v) => m.insert k v) {}

/-- Look up a keyword by its text. Returns none for non-keyword identifiers. -/
@[inline] def lookupKeyword (text : String) : Option SyntaxKind :=
  textToKeyword[text]?

/-- Map from SyntaxKind to the keyword text (reverse lookup). -/
def tokenToText : Std.HashMap SyntaxKind String :=
  let entries : Array (SyntaxKind × String) := #[
    -- Punctuation
    (.openBraceToken, "{"),
    (.closeBraceToken, "}"),
    (.openParenToken, "("),
    (.closeParenToken, ")"),
    (.openBracketToken, "["),
    (.closeBracketToken, "]"),
    (.dotToken, "."),
    (.dotDotDotToken, "..."),
    (.semicolonToken, ";"),
    (.commaToken, ","),
    (.lessThanToken, "<"),
    (.greaterThanToken, ">"),
    (.lessThanEqualsToken, "<="),
    (.greaterThanEqualsToken, ">="),
    (.equalsEqualsToken, "=="),
    (.exclamationEqualsToken, "!="),
    (.equalsEqualsEqualsToken, "==="),
    (.exclamationEqualsEqualsToken, "!=="),
    (.equalsGreaterThanToken, "=>"),
    (.plusToken, "+"),
    (.minusToken, "-"),
    (.asteriskToken, "*"),
    (.asteriskAsteriskToken, "**"),
    (.slashToken, "/"),
    (.percentToken, "%"),
    (.plusPlusToken, "++"),
    (.minusMinusToken, "--"),
    (.lessThanLessThanToken, "<<"),
    (.greaterThanGreaterThanToken, ">>"),
    (.greaterThanGreaterThanGreaterThanToken, ">>>"),
    (.ampersandToken, "&"),
    (.barToken, "|"),
    (.caretToken, "^"),
    (.exclamationToken, "!"),
    (.tildeToken, "~"),
    (.ampersandAmpersandToken, "&&"),
    (.barBarToken, "||"),
    (.questionToken, "?"),
    (.colonToken, ":"),
    (.equalsToken, "="),
    (.plusEqualsToken, "+="),
    (.minusEqualsToken, "-="),
    (.asteriskEqualsToken, "*="),
    (.asteriskAsteriskEqualsToken, "**="),
    (.slashEqualsToken, "/="),
    (.percentEqualsToken, "%="),
    (.lessThanLessThanEqualsToken, "<<="),
    (.greaterThanGreaterThanEqualsToken, ">>="),
    (.greaterThanGreaterThanGreaterThanEqualsToken, ">>>="),
    (.ampersandEqualsToken, "&="),
    (.barEqualsToken, "|="),
    (.caretEqualsToken, "^="),
    (.atToken, "@"),
    (.questionQuestionToken, "??"),
    (.questionDotToken, "?."),
    (.barBarEqualsToken, "||="),
    (.ampersandAmpersandEqualsToken, "&&="),
    (.questionQuestionEqualsToken, "??="),
    (.backtickToken, "`"),
    (.hashToken, "#"),
    -- Keywords
    (.breakKeyword, "break"),
    (.caseKeyword, "case"),
    (.catchKeyword, "catch"),
    (.classKeyword, "class"),
    (.constKeyword, "const"),
    (.continueKeyword, "continue"),
    (.debuggerKeyword, "debugger"),
    (.defaultKeyword, "default"),
    (.deleteKeyword, "delete"),
    (.doKeyword, "do"),
    (.elseKeyword, "else"),
    (.enumKeyword, "enum"),
    (.exportKeyword, "export"),
    (.extendsKeyword, "extends"),
    (.falseKeyword, "false"),
    (.finallyKeyword, "finally"),
    (.forKeyword, "for"),
    (.functionKeyword, "function"),
    (.ifKeyword, "if"),
    (.importKeyword, "import"),
    (.inKeyword, "in"),
    (.instanceOfKeyword, "instanceof"),
    (.newKeyword, "new"),
    (.nullKeyword, "null"),
    (.returnKeyword, "return"),
    (.superKeyword, "super"),
    (.switchKeyword, "switch"),
    (.thisKeyword, "this"),
    (.throwKeyword, "throw"),
    (.trueKeyword, "true"),
    (.tryKeyword, "try"),
    (.typeOfKeyword, "typeof"),
    (.varKeyword, "var"),
    (.voidKeyword, "void"),
    (.whileKeyword, "while"),
    (.withKeyword, "with")
  ]
  entries.foldl (fun m (k, v) => m.insert k v) {}

end TSLean.Scanner
